In [12]:
import numpy as np
import dask.dataframe as dd

In [13]:
#reading the file using dask
df = dd.read_csv('../data_preprocessing/osiris_toydata_6.csv', sep=' ', header=None)
df = df.rename(columns={0: "time", 1: "energy", 2: "x", 3: "y", 4: "z", 9: "truth"})

In [14]:
df.head()

,time,energy,x,y,z,5,6,7,8,truth
0,31735.462322,763.642980,-46.310073,-1409.756076,352.442788,0.0,0.0,0.0,0.0,3.0
1,31736.613083,478.788298,954.498700,-1153.308450,-423.933926,0.0,0.0,0.0,0.0,3.0
2,31738.604620,505.456848,-624.530649,-0.054240,1496.010881,0.0,0.0,0.0,0.0,3.0
3,31739.556162,349.150870,-1206.847394,-589.716672,-811.445496,0.0,0.0,0.0,0.0,3.0
4,31739.788782,111.914395,1091.482272,528.086234,-1178.998934,0.0,0.0,0.0,0.0,3.0

In [15]:
#dropping the empty clumns
df = df.drop([5,6,7,8], axis=1)

In [16]:
# Convert all columns to float
df = df.astype(float)

In [6]:
df.head()

           time       energy            x            y            z  truth
0  31588.165779   349.150870 -1206.847394  -589.716672  -811.445496    3.0
1  31588.472804   158.519760 -1134.030669   830.560976 -1464.948906    3.0
2  31589.893281   556.513047  1346.121107   -66.343729  -985.757136    3.0
3  31594.697900   579.893826  -405.390913  -548.771709 -1503.247408    3.0
4  31596.189344  1106.678890  -974.846291  1020.583659  -117.884822    0.0

In [17]:
df['truth'].value_counts().compute()

truth
3.0    6300000
0.0     433000
1.0       2707
2.0       2707
4.0        902
5.0        902
Name: count, dtype: int64